sudo: required

language: rust

rust:
- stable

os:
- linux

before_install:
- sudo apt update

install:
- sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
- sudo apt-get install libsdl2-dev

script:
- cargo build -v
