sudo: required

cache: cargo

language: rust

rust:
  - stable
  - nightly
  
matrix:
  allow_failures:
    - rust: nightly
fast_finish: true

os:
- linux

before_install:
- sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev
- sudo apt-get install libsdl2-dev
addons:
  apt:
    update: true

script:
- cargo build -v
